# Generated by Django 5.0.1 on 2024-07-04 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comment_item_user_comments_auctionlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='comments',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionlisting'),
        ),
    ]
