# Generated by Django 5.0.1 on 2024-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_user_comments_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='items',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
