# Generated by Django 5.0.1 on 2024-07-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auctionlisting_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='comments',
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='img',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=64),
        ),
    ]
